### ISSUE TITLE
[Help] Using this package

### ISSUE THREAD

**Issue by SirNeural** [codekraft-studio/vorpal#12]
Hi,
Saw this fork as a up-to-date version of vorpal with updated dependencies and typescript, but I'm not sure how to pull this package in to my project to use it.
Using the official vorpal would be a simple `yarn add vorpal`, but now trying to manually add it through github using the command `yarn add https://github.com/codekraft-studio/vorpal` works without error, but on runtime produces the following error `Error: Cannot find module './common`, with the stacktrace pointing to `\node_modules\vorpal\dist\index.js:12:16'`, referencing a require() call to `./common` which doesn't exist in the dist directory. Trying to pin to a prior commit without the dist directory (commit # a9ffe32c12c76527da039376d6bb88528b37989e) causes a different error because the .ts files need to be compiled down to regular .js files.

Is there any recommended way to add this into a project? I really appreciate the effort into maintaining a fork of vorpal since the original and its dependencies are way out of date and haven't been updated in a while.

Thanks!

**Comment by b4dnewz** [comment]
hi @SirNeural thanks for pointing this out, it's an error that I produced when trying to build the definitions in my last commit, actually I haven't migrated all files to ts so I can't produce declarations and allowJs at the same time, now I'll push new commit 17a6e2c348590295b5e1ed3430eb5debb3b0f9fc with the files that are missing.

you can use this form: `npm i codekraft-studio/vorpal` to get the github master or `npm i codekraft-studio/vorpal@commit` to get a specific commit.

I've tested locally and seems to work, but while compiling some definitions produces error, I still need to fix them.

Btw, I suggest to you to pin a specific working commit and rely on that until I ended the migration and moved the repository in a dedicated npm module (not a fork anymore)

```json
"dependencies": {
    "vorpal": "github:codekraft-studio/vorpal#17a6e2c348590295b5e1ed3430eb5debb3b0f9fc"
 }
```

**Comment by SirNeural** [comment]
HI @b4dnewz,
I've added this project and pinned in my package.json to commit 17a6e2c348590295b5e1ed3430eb5debb3b0f9fc, however trying to require it using the following code given by the official Vorpal docs, `const vorpal = require('vorpal')()` gives an error, and it looking through seems that since I am not using import syntax I need to import it as `const vorpal = require('vorpal').default()`, however that still gives an error, `TypeError: _this._init is not a function`.
Is there a difference in import syntax required to import and initialize with require()?

Thanks!

**Comment by b4dnewz** [comment]
@SirNeural it's a known ts issue, by default the build doesn't expose the default property as es6 does for example, if you want to use it with normal javascript/es6 you must do:

```js
const Vorpal = require('vorpal').default;
```

otherwise with ts you can use import:
```ts
import Vorpal from 'Vorpal';
```

**Comment by b4dnewz** [comment]
@SirNeural have you solved it?
